### ISSUE TITLE
Enable POSIX suppprt

### ISSUE THREAD

**Issue by AloisAUBIN** [mgrosperrin/commandlineparser#63]
Example: myprogram.exe --name Matthias /
myprogram.exe -n Matthias

**Comment by mgrosperrin** [comment]
This syntax (`--`/`-` for long/short form to specify options) is available since 0.10.0.
The name of the options can be customized to be lower case (instead of the case of the property name) using the `System.ComponentModel.DataAnnotations.DisplayAttribute`.

A future version (probably 0.11.0) will default the long form name of the option to be kebab case.
